name: PlanetPortland
favicon: null
layout_spectrum: 0.017540005268529058
typography_spectrum: 0.1459585304837674
title: Planet Portland
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1b1b1b'
    - '#606062'
    - '#ababad'
    - '#3bab00'
    - '#f9f9f9'
  brandStrength: 0.5
  lightness: 0.5068820479791611
  saturation: 0.21183843235485256
  rhythmicContrast: 0.5744211983401328
purpose: []
